subdir-ccflags-y += -Werror
obj-y += fuse/

obj-y += common.o
obj-y += flowctrl.o
obj-y += pmc.o
obj-y += cvb.o
obj-$(CONFIG_TEGRA_BPMP_MAILMAN) += tegra-bpmp-mailman.o

obj-$(CONFIG_ARCH_TEGRA_210_SOC)    += pmc-reboot2payload.o
